CREATE TABLE `countries` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`iso` char(2) DEFAULT NULL,
`nombre` varchar(80) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
 
INSERT INTO `countries` VALUES(1, 'AF', 'Afganistán',null,null);
INSERT INTO `countries` VALUES(2, 'AX', 'Islas Gland',null,null);
INSERT INTO `countries` VALUES(3, 'AL', 'Albania',null,null);
INSERT INTO `countries` VALUES(4, 'DE', 'Alemania',null,null);
INSERT INTO `countries` VALUES(5, 'AD', 'Andorra',null,null);
INSERT INTO `countries` VALUES(6, 'AO', 'Angola',null,null);
INSERT INTO `countries` VALUES(7, 'AI', 'Anguilla',null,null);
INSERT INTO `countries` VALUES(8, 'AQ', 'Antártida',null,null);
INSERT INTO `countries` VALUES(9, 'AG', 'Antigua y Barbuda',null,null);
INSERT INTO `countries` VALUES(10, 'AN', 'Antillas Holandesas',null,null);
INSERT INTO `countries` VALUES(11, 'SA', 'Arabia Saudí',null,null);
INSERT INTO `countries` VALUES(12, 'DZ', 'Argelia',null,null);
INSERT INTO `countries` VALUES(13, 'AR', 'Argentina',null,null);
INSERT INTO `countries` VALUES(14, 'AM', 'Armenia',null,null);
INSERT INTO `countries` VALUES(15, 'AW', 'Aruba',null,null);
INSERT INTO `countries` VALUES(16, 'AU', 'Australia',null,null);
INSERT INTO `countries` VALUES(17, 'AT', 'Austria',null,null);
INSERT INTO `countries` VALUES(18, 'AZ', 'Azerbaiyán',null,null);
INSERT INTO `countries` VALUES(19, 'BS', 'Bahamas',null,null);
INSERT INTO `countries` VALUES(20, 'BH', 'Bahréin',null,null);
INSERT INTO `countries` VALUES(21, 'BD', 'Bangladesh',null,null);
INSERT INTO `countries` VALUES(22, 'BB', 'Barbados',null,null);
INSERT INTO `countries` VALUES(23, 'BY', 'Bielorrusia',null,null);
INSERT INTO `countries` VALUES(24, 'BE', 'Bélgica',null,null);
INSERT INTO `countries` VALUES(25, 'BZ', 'Belice',null,null);
INSERT INTO `countries` VALUES(26, 'BJ', 'Benin',null,null);
INSERT INTO `countries` VALUES(27, 'BM', 'Bermudas',null,null);
INSERT INTO `countries` VALUES(28, 'BT', 'Bhután',null,null);
INSERT INTO `countries` VALUES(29, 'BO', 'Bolivia',null,null);
INSERT INTO `countries` VALUES(30, 'BA', 'Bosnia y Herzegovina',null,null);
INSERT INTO `countries` VALUES(31, 'BW', 'Botsuana',null,null);
INSERT INTO `countries` VALUES(32, 'BV', 'Isla Bouvet',null,null);
INSERT INTO `countries` VALUES(33, 'BR', 'Brasil',null,null);
INSERT INTO `countries` VALUES(34, 'BN', 'Brunéi',null,null);
INSERT INTO `countries` VALUES(35, 'BG', 'Bulgaria',null,null);
INSERT INTO `countries` VALUES(36, 'BF', 'Burkina Faso',null,null);
INSERT INTO `countries` VALUES(37, 'BI', 'Burundi',null,null);
INSERT INTO `countries` VALUES(38, 'CV', 'Cabo Verde',null,null);
INSERT INTO `countries` VALUES(39, 'KY', 'Islas Caimán',null,null);
INSERT INTO `countries` VALUES(40, 'KH', 'Camboya',null,null);
INSERT INTO `countries` VALUES(41, 'CM', 'Camerún',null,null);
INSERT INTO `countries` VALUES(42, 'CA', 'Canadá',null,null);
INSERT INTO `countries` VALUES(43, 'CF', 'República Centroafricana',null,null);
INSERT INTO `countries` VALUES(44, 'TD', 'Chad',null,null);
INSERT INTO `countries` VALUES(45, 'CZ', 'República Checa',null,null);
INSERT INTO `countries` VALUES(46, 'CL', 'Chile',null,null);
INSERT INTO `countries` VALUES(47, 'CN', 'China',null,null);
INSERT INTO `countries` VALUES(48, 'CY', 'Chipre',null,null);
INSERT INTO `countries` VALUES(49, 'CX', 'Isla de Navidad',null,null);
INSERT INTO `countries` VALUES(50, 'VA', 'Ciudad del Vaticano',null,null);
INSERT INTO `countries` VALUES(51, 'CC', 'Islas Cocos',null,null);
INSERT INTO `countries` VALUES(52, 'CO', 'Colombia',null,null);
INSERT INTO `countries` VALUES(53, 'KM', 'Comoras',null,null);
INSERT INTO `countries` VALUES(54, 'CD', 'República Democrática del Congo',null,null);
INSERT INTO `countries` VALUES(55, 'CG', 'Congo',null,null);
INSERT INTO `countries` VALUES(56, 'CK', 'Islas Cook',null,null);
INSERT INTO `countries` VALUES(57, 'KP', 'Corea del Norte',null,null);
INSERT INTO `countries` VALUES(58, 'KR', 'Corea del Sur',null,null);
INSERT INTO `countries` VALUES(59, 'CI', 'Costa de Marfil',null,null);
INSERT INTO `countries` VALUES(60, 'CR', 'Costa Rica',null,null);
INSERT INTO `countries` VALUES(61, 'HR', 'Croacia',null,null);
INSERT INTO `countries` VALUES(62, 'CU', 'Cuba',null,null);
INSERT INTO `countries` VALUES(63, 'DK', 'Dinamarca',null,null);
INSERT INTO `countries` VALUES(64, 'DM', 'Dominica',null,null);
INSERT INTO `countries` VALUES(65, 'DO', 'República Dominicana',null,null);
INSERT INTO `countries` VALUES(66, 'EC', 'Ecuador',null,null);
INSERT INTO `countries` VALUES(67, 'EG', 'Egipto',null,null);
INSERT INTO `countries` VALUES(68, 'SV', 'El Salvador',null,null);
INSERT INTO `countries` VALUES(69, 'AE', 'Emiratos Árabes Unidos',null,null);
INSERT INTO `countries` VALUES(70, 'ER', 'Eritrea',null,null);
INSERT INTO `countries` VALUES(71, 'SK', 'Eslovaquia',null,null);
INSERT INTO `countries` VALUES(72, 'SI', 'Eslovenia',null,null);
INSERT INTO `countries` VALUES(73, 'ES', 'España',null,null);
INSERT INTO `countries` VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos',null,null);
INSERT INTO `countries` VALUES(75, 'US', 'Estados Unidos',null,null);
INSERT INTO `countries` VALUES(76, 'EE', 'Estonia',null,null);
INSERT INTO `countries` VALUES(77, 'ET', 'Etiopía',null,null);
INSERT INTO `countries` VALUES(78, 'FO', 'Islas Feroe',null,null);
INSERT INTO `countries` VALUES(79, 'PH', 'Filipinas',null,null);
INSERT INTO `countries` VALUES(80, 'FI', 'Finlandia',null,null);
INSERT INTO `countries` VALUES(81, 'FJ', 'Fiyi',null,null);
INSERT INTO `countries` VALUES(82, 'FR', 'Francia',null,null);
INSERT INTO `countries` VALUES(83, 'GA', 'Gabón',null,null);
INSERT INTO `countries` VALUES(84, 'GM', 'Gambia',null,null);
INSERT INTO `countries` VALUES(85, 'GE', 'Georgia',null,null);
INSERT INTO `countries` VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur',null,null);
INSERT INTO `countries` VALUES(87, 'GH', 'Ghana',null,null);
INSERT INTO `countries` VALUES(88, 'GI', 'Gibraltar',null,null);
INSERT INTO `countries` VALUES(89, 'GD', 'Granada',null,null);
INSERT INTO `countries` VALUES(90, 'GR', 'Grecia',null,null);
INSERT INTO `countries` VALUES(91, 'GL', 'Groenlandia',null,null);
INSERT INTO `countries` VALUES(92, 'GP', 'Guadalupe',null,null);
INSERT INTO `countries` VALUES(93, 'GU', 'Guam',null,null);
INSERT INTO `countries` VALUES(94, 'GT', 'Guatemala',null,null);
INSERT INTO `countries` VALUES(95, 'GF', 'Guayana Francesa',null,null);
INSERT INTO `countries` VALUES(96, 'GN', 'Guinea',null,null);
INSERT INTO `countries` VALUES(97, 'GQ', 'Guinea Ecuatorial',null,null);
INSERT INTO `countries` VALUES(98, 'GW', 'Guinea-Bissau',null,null);
INSERT INTO `countries` VALUES(99, 'GY', 'Guyana',null,null);
INSERT INTO `countries` VALUES(100, 'HT', 'Haití',null,null);
INSERT INTO `countries` VALUES(101, 'HM', 'Islas Heard y McDonald',null,null);
INSERT INTO `countries` VALUES(102, 'HN', 'Honduras',null,null);
INSERT INTO `countries` VALUES(103, 'HK', 'Hong Kong',null,null);
INSERT INTO `countries` VALUES(104, 'HU', 'Hungría',null,null);
INSERT INTO `countries` VALUES(105, 'IN', 'India',null,null);
INSERT INTO `countries` VALUES(106, 'ID', 'Indonesia',null,null);
INSERT INTO `countries` VALUES(107, 'IR', 'Irán',null,null);
INSERT INTO `countries` VALUES(108, 'IQ', 'Iraq',null,null);
INSERT INTO `countries` VALUES(109, 'IE', 'Irlanda',null,null);
INSERT INTO `countries` VALUES(110, 'IS', 'Islandia',null,null);
INSERT INTO `countries` VALUES(111, 'IL', 'Israel',null,null);
INSERT INTO `countries` VALUES(112, 'IT', 'Italia',null,null);
INSERT INTO `countries` VALUES(113, 'JM', 'Jamaica',null,null);
INSERT INTO `countries` VALUES(114, 'JP', 'Japón',null,null);
INSERT INTO `countries` VALUES(115, 'JO', 'Jordania',null,null);
INSERT INTO `countries` VALUES(116, 'KZ', 'Kazajstán',null,null);
INSERT INTO `countries` VALUES(117, 'KE', 'Kenia',null,null);
INSERT INTO `countries` VALUES(118, 'KG', 'Kirguistán',null,null);
INSERT INTO `countries` VALUES(119, 'KI', 'Kiribati',null,null);
INSERT INTO `countries` VALUES(120, 'KW', 'Kuwait',null,null);
INSERT INTO `countries` VALUES(121, 'LA', 'Laos',null,null);
INSERT INTO `countries` VALUES(122, 'LS', 'Lesotho',null,null);
INSERT INTO `countries` VALUES(123, 'LV', 'Letonia',null,null);
INSERT INTO `countries` VALUES(124, 'LB', 'Líbano',null,null);
INSERT INTO `countries` VALUES(125, 'LR', 'Liberia',null,null);
INSERT INTO `countries` VALUES(126, 'LY', 'Libia',null,null);
INSERT INTO `countries` VALUES(127, 'LI', 'Liechtenstein',null,null);
INSERT INTO `countries` VALUES(128, 'LT', 'Lituania',null,null);
INSERT INTO `countries` VALUES(129, 'LU', 'Luxemburgo',null,null);
INSERT INTO `countries` VALUES(130, 'MO', 'Macao',null,null);
INSERT INTO `countries` VALUES(131, 'MK', 'ARY Macedonia',null,null);
INSERT INTO `countries` VALUES(132, 'MG', 'Madagascar',null,null);
INSERT INTO `countries` VALUES(133, 'MY', 'Malasia',null,null);
INSERT INTO `countries` VALUES(134, 'MW', 'Malawi',null,null);
INSERT INTO `countries` VALUES(135, 'MV', 'Maldivas',null,null);
INSERT INTO `countries` VALUES(136, 'ML', 'Malí',null,null);
INSERT INTO `countries` VALUES(137, 'MT', 'Malta',null,null);
INSERT INTO `countries` VALUES(138, 'FK', 'Islas Malvinas',null,null);
INSERT INTO `countries` VALUES(139, 'MP', 'Islas Marianas del Norte',null,null);
INSERT INTO `countries` VALUES(140, 'MA', 'Marruecos',null,null);
INSERT INTO `countries` VALUES(141, 'MH', 'Islas Marshall',null,null);
INSERT INTO `countries` VALUES(142, 'MQ', 'Martinica',null,null);
INSERT INTO `countries` VALUES(143, 'MU', 'Mauricio',null,null);
INSERT INTO `countries` VALUES(144, 'MR', 'Mauritania',null,null);
INSERT INTO `countries` VALUES(145, 'YT', 'Mayotte',null,null);
INSERT INTO `countries` VALUES(146, 'MX', 'México',null,null);
INSERT INTO `countries` VALUES(147, 'FM', 'Micronesia',null,null);
INSERT INTO `countries` VALUES(148, 'MD', 'Moldavia',null,null);
INSERT INTO `countries` VALUES(149, 'MC', 'Mónaco',null,null);
INSERT INTO `countries` VALUES(150, 'MN', 'Mongolia',null,null);
INSERT INTO `countries` VALUES(151, 'MS', 'Montserrat',null,null);
INSERT INTO `countries` VALUES(152, 'MZ', 'Mozambique',null,null);
INSERT INTO `countries` VALUES(153, 'MM', 'Myanmar',null,null);
INSERT INTO `countries` VALUES(154, 'NA', 'Namibia',null,null);
INSERT INTO `countries` VALUES(155, 'NR', 'Nauru',null,null);
INSERT INTO `countries` VALUES(156, 'NP', 'Nepal',null,null);
INSERT INTO `countries` VALUES(157, 'NI', 'Nicaragua',null,null);
INSERT INTO `countries` VALUES(158, 'NE', 'Níger',null,null);
INSERT INTO `countries` VALUES(159, 'NG', 'Nigeria',null,null);
INSERT INTO `countries` VALUES(160, 'NU', 'Niue',null,null);
INSERT INTO `countries` VALUES(161, 'NF', 'Isla Norfolk',null,null);
INSERT INTO `countries` VALUES(162, 'NO', 'Noruega',null,null);
INSERT INTO `countries` VALUES(163, 'NC', 'Nueva Caledonia',null,null);
INSERT INTO `countries` VALUES(164, 'NZ', 'Nueva Zelanda',null,null);
INSERT INTO `countries` VALUES(165, 'OM', 'Omán',null,null);
INSERT INTO `countries` VALUES(166, 'NL', 'Países Bajos',null,null);
INSERT INTO `countries` VALUES(167, 'PK', 'Pakistán',null,null);
INSERT INTO `countries` VALUES(168, 'PW', 'Palau',null,null);
INSERT INTO `countries` VALUES(169, 'PS', 'Palestina',null,null);
INSERT INTO `countries` VALUES(170, 'PA', 'Panamá',null,null);
INSERT INTO `countries` VALUES(171, 'PG', 'Papúa Nueva Guinea',null,null);
INSERT INTO `countries` VALUES(172, 'PY', 'Paraguay',null,null);
INSERT INTO `countries` VALUES(173, 'PE', 'Perú',null,null);
INSERT INTO `countries` VALUES(174, 'PN', 'Islas Pitcairn',null,null);
INSERT INTO `countries` VALUES(175, 'PF', 'Polinesia Francesa',null,null);
INSERT INTO `countries` VALUES(176, 'PL', 'Polonia',null,null);
INSERT INTO `countries` VALUES(177, 'PT', 'Portugal',null,null);
INSERT INTO `countries` VALUES(178, 'PR', 'Puerto Rico',null,null);
INSERT INTO `countries` VALUES(179, 'QA', 'Qatar',null,null);
INSERT INTO `countries` VALUES(180, 'GB', 'Reino Unido',null,null);
INSERT INTO `countries` VALUES(181, 'RE', 'Reunión',null,null);
INSERT INTO `countries` VALUES(182, 'RW', 'Ruanda',null,null);
INSERT INTO `countries` VALUES(183, 'RO', 'Rumania',null,null);
INSERT INTO `countries` VALUES(184, 'RU', 'Rusia',null,null);
INSERT INTO `countries` VALUES(185, 'EH', 'Sahara Occidental',null,null);
INSERT INTO `countries` VALUES(186, 'SB', 'Islas Salomón',null,null);
INSERT INTO `countries` VALUES(187, 'WS', 'Samoa',null,null);
INSERT INTO `countries` VALUES(188, 'AS', 'Samoa Americana',null,null);
INSERT INTO `countries` VALUES(189, 'KN', 'San Cristóbal y Nevis',null,null);
INSERT INTO `countries` VALUES(190, 'SM', 'San Marino',null,null);
INSERT INTO `countries` VALUES(191, 'PM', 'San Pedro y Miquelón',null,null);
INSERT INTO `countries` VALUES(192, 'VC', 'San Vicente y las Granadinas',null,null);
INSERT INTO `countries` VALUES(193, 'SH', 'Santa Helena',null,null);
INSERT INTO `countries` VALUES(194, 'LC', 'Santa Lucía',null,null);
INSERT INTO `countries` VALUES(195, 'ST', 'Santo Tomé y Príncipe',null,null);
INSERT INTO `countries` VALUES(196, 'SN', 'Senegal',null,null);
INSERT INTO `countries` VALUES(197, 'CS', 'Serbia y Montenegro',null,null);
INSERT INTO `countries` VALUES(198, 'SC', 'Seychelles',null,null);
INSERT INTO `countries` VALUES(199, 'SL', 'Sierra Leona',null,null);
INSERT INTO `countries` VALUES(200, 'SG', 'Singapur',null,null);
INSERT INTO `countries` VALUES(201, 'SY', 'Siria',null,null);
INSERT INTO `countries` VALUES(202, 'SO', 'Somalia',null,null);
INSERT INTO `countries` VALUES(203, 'LK', 'Sri Lanka',null,null);
INSERT INTO `countries` VALUES(204, 'SZ', 'Suazilandia',null,null);
INSERT INTO `countries` VALUES(205, 'ZA', 'Sudáfrica',null,null);
INSERT INTO `countries` VALUES(206, 'SD', 'Sudán',null,null);
INSERT INTO `countries` VALUES(207, 'SE', 'Suecia',null,null);
INSERT INTO `countries` VALUES(208, 'CH', 'Suiza',null,null);
INSERT INTO `countries` VALUES(209, 'SR', 'Surinam',null,null);
INSERT INTO `countries` VALUES(210, 'SJ', 'Svalbard y Jan Mayen',null,null);
INSERT INTO `countries` VALUES(211, 'TH', 'Tailandia',null,null);
INSERT INTO `countries` VALUES(212, 'TW', 'Taiwán',null,null);
INSERT INTO `countries` VALUES(213, 'TZ', 'Tanzania',null,null);
INSERT INTO `countries` VALUES(214, 'TJ', 'Tayikistán',null,null);
INSERT INTO `countries` VALUES(215, 'IO', 'Territorio Británico del Océano Índico',null,null);
INSERT INTO `countries` VALUES(216, 'TF', 'Territorios Australes Franceses',null,null);
INSERT INTO `countries` VALUES(217, 'TL', 'Timor Oriental',null,null);
INSERT INTO `countries` VALUES(218, 'TG', 'Togo',null,null);
INSERT INTO `countries` VALUES(219, 'TK', 'Tokelau',null,null);
INSERT INTO `countries` VALUES(220, 'TO', 'Tonga',null,null);
INSERT INTO `countries` VALUES(221, 'TT', 'Trinidad y Tobago',null,null);
INSERT INTO `countries` VALUES(222, 'TN', 'Túnez',null,null);
INSERT INTO `countries` VALUES(223, 'TC', 'Islas Turcas y Caicos',null,null);
INSERT INTO `countries` VALUES(224, 'TM', 'Turkmenistán',null,null);
INSERT INTO `countries` VALUES(225, 'TR', 'Turquía',null,null);
INSERT INTO `countries` VALUES(226, 'TV', 'Tuvalu',null,null);
INSERT INTO `countries` VALUES(227, 'UA', 'Ucrania',null,null);
INSERT INTO `countries` VALUES(228, 'UG', 'Uganda',null,null);
INSERT INTO `countries` VALUES(229, 'UY', 'Uruguay',null,null);
INSERT INTO `countries` VALUES(230, 'UZ', 'Uzbekistán',null,null);
INSERT INTO `countries` VALUES(231, 'VU', 'Vanuatu',null,null);
INSERT INTO `countries` VALUES(232, 'VE', 'Venezuela',null,null);
INSERT INTO `countries` VALUES(233, 'VN', 'Vietnam',null,null);
INSERT INTO `countries` VALUES(234, 'VG', 'Islas Vírgenes Británicas',null,null);
INSERT INTO `countries` VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos',null,null);
INSERT INTO `countries` VALUES(236, 'WF', 'Wallis y Futuna',null,null);
INSERT INTO `countries` VALUES(237, 'YE', 'Yemen',null,null);
INSERT INTO `countries` VALUES(238, 'DJ', 'Yibuti',null,null);
INSERT INTO `countries` VALUES(239, 'ZM', 'Zambia',null,null);
INSERT INTO `countries` VALUES(240, 'ZW', 'Zimbabue',null,null);